# Generated by Django 4.0.4 on 2022-05-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220428_1420'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_non_subcriber',
        ),
    ]
